### ISSUE TITLE
modern-manabaのサイドメニューと競合する

### ISSUE THREAD

**Issue by momeemt** [slimalized/M-TimeTable#1]
<img width="939" alt="234796520-99f8b9a3-5a54-4f7f-96b8-180a26aca1f0" src="https://user-images.githubusercontent.com/43488453/234804807-de4a9e5c-0f22-4c16-b3af-f5dcd8855393.png">

[modern-manaba](https://chrome.google.com/webstore/detail/modern-manaba/oimcohooopcpjnmdgijjicdhkifopbli/related)で追加されるサイドメニューと、時間割のヘッダー部分が競合します。

原因としては、[modern-manabaのサイドメニューのz-index](https://github.com/itsu-dev/modern-manaba/blob/master/src/header.css#L218)と[M-TimeTableのヘッダのz-index](https://github.com/slimalized/M-TimeTable/blob/main/style/style.scss#L34)が一致していることです。  
両方とも利用している筑波大生は一定数いると思われますので、こちらの`z-index`を少し下げた方が使いやすさが向上すると思いました。

**Comment by slimalized** [comment]
ご連絡ありがとうございます。手元でも競合を確認いたしましたのでプルリクをマージさせていただきます。
